# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install --global vercel
    vercel pull --yes --environment=production --token=$(vercel-token)
    vercel build --prod --token=$(vercel-token)
    vercel deploy --prod --token=$(vercel-token)
  displayName: 'install and build vercel and deploy'
  workingDirectory: $(System.DefaultWorkingDirectory)
